export interface City {
  name: string
  country: string
  iata?: string   // primary airport code, where known
}

export const COUNTRY_FLAGS: Record<string, string> = {
  'India': '🇮🇳', 'Thailand': '🇹🇭', 'Indonesia': '🇮🇩', 'Singapore': '🇸🇬',
  'UAE': '🇦🇪', 'Malaysia': '🇲🇾', 'UK': '🇬🇧', 'France': '🇫🇷',
  'USA': '🇺🇸', 'Canada': '🇨🇦', 'Australia': '🇦🇺', 'Sri Lanka': '🇱🇰',
  'Nepal': '🇳🇵', 'Bangladesh': '🇧🇩', 'Oman': '🇴🇲', 'Qatar': '🇶🇦',
  'Saudi Arabia': '🇸🇦', 'Germany': '🇩🇪', 'Netherlands': '🇳🇱', 'Japan': '🇯🇵',
  'Hong Kong': '🇭🇰', 'Kenya': '🇰🇪', 'Maldives': '🇲🇻',
}

export const CITIES: City[] = [
  // ── India ────────────────────────────────────────────────────────────────
  { name: 'Agartala',       country: 'India', iata: 'IXA' },
  { name: 'Agra',           country: 'India', iata: 'AGR' },
  { name: 'Ahmedabad',      country: 'India', iata: 'AMD' },
  { name: 'Aizawl',         country: 'India', iata: 'AJL' },
  { name: 'Amritsar',       country: 'India', iata: 'ATQ' },
  { name: 'Aurangabad',     country: 'India', iata: 'IXU' },
  { name: 'Ayodhya',        country: 'India', iata: 'AYJ' },
  { name: 'Bagdogra',       country: 'India', iata: 'IXB' },
  { name: 'Bangalore',      country: 'India', iata: 'BLR' },
  { name: 'Belgaum',        country: 'India', iata: 'IXG' },
  { name: 'Bhavnagar',      country: 'India', iata: 'BHU' },
  { name: 'Bhopal',         country: 'India', iata: 'BHO' },
  { name: 'Bhubaneswar',    country: 'India', iata: 'BBI' },
  { name: 'Chandigarh',     country: 'India', iata: 'IXC' },
  { name: 'Chennai',        country: 'India', iata: 'MAA' },
  { name: 'Coimbatore',     country: 'India', iata: 'CJB' },
  { name: 'Dehradun',       country: 'India', iata: 'DED' },
  { name: 'Delhi',          country: 'India', iata: 'DEL' },
  { name: 'Dharamsala',     country: 'India', iata: 'DHM' },
  { name: 'Dibrugarh',      country: 'India', iata: 'DIB' },
  { name: 'Diu',            country: 'India', iata: 'DIU' },
  { name: 'Goa',            country: 'India', iata: 'GOI' },
  { name: 'Gorakhpur',      country: 'India', iata: 'GOP' },
  { name: 'Guwahati',       country: 'India', iata: 'GAU' },
  { name: 'Gwalior',        country: 'India', iata: 'GWL' },
  { name: 'Hubli',          country: 'India', iata: 'HBX' },
  { name: 'Hyderabad',      country: 'India', iata: 'HYD' },
  { name: 'Imphal',         country: 'India', iata: 'IMF' },
  { name: 'Indore',         country: 'India', iata: 'IDR' },
  { name: 'Itanagar',       country: 'India', iata: 'HGI' },
  { name: 'Jabalpur',       country: 'India', iata: 'JLR' },
  { name: 'Jaipur',         country: 'India', iata: 'JAI' },
  { name: 'Jammu',          country: 'India', iata: 'IXJ' },
  { name: 'Jamnagar',       country: 'India', iata: 'JGA' },
  { name: 'Jodhpur',        country: 'India', iata: 'JDH' },
  { name: 'Jorhat',         country: 'India', iata: 'JRH' },
  { name: 'Kannur',         country: 'India', iata: 'CNN' },
  { name: 'Khajuraho',      country: 'India', iata: 'HJR' },
  { name: 'Kochi',          country: 'India', iata: 'COK' },
  { name: 'Kolkata',        country: 'India', iata: 'CCU' },
  { name: 'Kozhikode',      country: 'India', iata: 'CCJ' },
  { name: 'Kullu',          country: 'India', iata: 'KUU' },
  { name: 'Leh',            country: 'India', iata: 'IXL' },
  { name: 'Lucknow',        country: 'India', iata: 'LKO' },
  { name: 'Madurai',        country: 'India', iata: 'IXM' },
  { name: 'Mangalore',      country: 'India', iata: 'IXE' },
  { name: 'Mumbai',         country: 'India', iata: 'BOM' },
  { name: 'Mysore',         country: 'India', iata: 'MYQ' },
  { name: 'Nagpur',         country: 'India', iata: 'NAG' },
  { name: 'Patna',          country: 'India', iata: 'PAT' },
  { name: 'Port Blair',     country: 'India', iata: 'IXZ' },
  { name: 'Pune',           country: 'India', iata: 'PNQ' },
  { name: 'Raipur',         country: 'India', iata: 'RPR' },
  { name: 'Rajkot',         country: 'India', iata: 'RAJ' },
  { name: 'Ranchi',         country: 'India', iata: 'IXR' },
  { name: 'Shillong',       country: 'India', iata: 'SHL' },
  { name: 'Shimla',         country: 'India', iata: 'SLV' },
  { name: 'Silchar',        country: 'India', iata: 'IXS' },
  { name: 'Srinagar',       country: 'India', iata: 'SXR' },
  { name: 'Surat',          country: 'India', iata: 'STV' },
  { name: 'Tirupati',       country: 'India', iata: 'TIR' },
  { name: 'Tiruchirappalli',country: 'India', iata: 'TRZ' },
  { name: 'Udaipur',        country: 'India', iata: 'UDR' },
  { name: 'Vadodara',       country: 'India', iata: 'BDQ' },
  { name: 'Varanasi',       country: 'India', iata: 'VNS' },
  { name: 'Vijayawada',     country: 'India', iata: 'VGA' },
  { name: 'Thiruvananthapuram', country: 'India', iata: 'TRV' },
  { name: 'Visakhapatnam',  country: 'India', iata: 'VTZ' },

  // ── Popular international destinations for Indian travelers ──────────────
  { name: 'Bangkok',        country: 'Thailand',     iata: 'BKK' },
  { name: 'Phuket',         country: 'Thailand',     iata: 'HKT' },
  { name: 'Bali',           country: 'Indonesia',    iata: 'DPS' },
  { name: 'Singapore',      country: 'Singapore',    iata: 'SIN' },
  { name: 'Dubai',          country: 'UAE',          iata: 'DXB' },
  { name: 'Abu Dhabi',      country: 'UAE',          iata: 'AUH' },
  { name: 'Kuala Lumpur',   country: 'Malaysia',     iata: 'KUL' },
  { name: 'London',         country: 'UK',           iata: 'LHR' },
  { name: 'Paris',          country: 'France',       iata: 'CDG' },
  { name: 'New York',       country: 'USA',          iata: 'JFK' },
  { name: 'Toronto',        country: 'Canada',       iata: 'YYZ' },
  { name: 'Sydney',         country: 'Australia',    iata: 'SYD' },
  { name: 'Melbourne',      country: 'Australia',    iata: 'MEL' },
  { name: 'Colombo',        country: 'Sri Lanka',    iata: 'CMB' },
  { name: 'Kathmandu',      country: 'Nepal',        iata: 'KTM' },
  { name: 'Male',           country: 'Maldives',     iata: 'MLE' },
  { name: 'Dhaka',          country: 'Bangladesh',   iata: 'DAC' },
  { name: 'Muscat',         country: 'Oman',         iata: 'MCT' },
  { name: 'Doha',           country: 'Qatar',        iata: 'DOH' },
  { name: 'Riyadh',         country: 'Saudi Arabia', iata: 'RUH' },
  { name: 'Frankfurt',      country: 'Germany',      iata: 'FRA' },
  { name: 'Amsterdam',      country: 'Netherlands',  iata: 'AMS' },
  { name: 'Tokyo',          country: 'Japan',        iata: 'NRT' },
  { name: 'Hong Kong',      country: 'Hong Kong',    iata: 'HKG' },
  { name: 'Nairobi',        country: 'Kenya',        iata: 'NBO' },
]

// Plain name list for backward compatibility (used in CityDropdown filtering)
export const CITY_NAMES = CITIES.map(c => c.name)
